package com.imooc.pojo;

import java.util.Date;

public class CarStatuses {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.created_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.updated_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.car_no
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String carNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.create_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.update_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.last_in_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date lastInTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.last_out_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date lastOutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.visit_count
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Integer visitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.status
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.last_group_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String lastGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.last_floor
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String lastFloor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.last_position_x
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Integer lastPositionX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.last_position_y
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Integer lastPositionY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.last_node_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String lastNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.image_url
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.velocity_x
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Double velocityX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.velocity_y
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Double velocityY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_statuses.velocity_ts
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Long velocityTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.id
     *
     * @return the value of car_statuses.id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.id
     *
     * @param id the value for car_statuses.id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.created_at
     *
     * @return the value of car_statuses.created_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.created_at
     *
     * @param createdAt the value for car_statuses.created_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.updated_at
     *
     * @return the value of car_statuses.updated_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.updated_at
     *
     * @param updatedAt the value for car_statuses.updated_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.car_no
     *
     * @return the value of car_statuses.car_no
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getCarNo() {
        return carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.car_no
     *
     * @param carNo the value for car_statuses.car_no
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setCarNo(String carNo) {
        this.carNo = carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.create_time
     *
     * @return the value of car_statuses.create_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.create_time
     *
     * @param createTime the value for car_statuses.create_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.update_time
     *
     * @return the value of car_statuses.update_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.update_time
     *
     * @param updateTime the value for car_statuses.update_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.last_in_time
     *
     * @return the value of car_statuses.last_in_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getLastInTime() {
        return lastInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.last_in_time
     *
     * @param lastInTime the value for car_statuses.last_in_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLastInTime(Date lastInTime) {
        this.lastInTime = lastInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.last_out_time
     *
     * @return the value of car_statuses.last_out_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getLastOutTime() {
        return lastOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.last_out_time
     *
     * @param lastOutTime the value for car_statuses.last_out_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLastOutTime(Date lastOutTime) {
        this.lastOutTime = lastOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.visit_count
     *
     * @return the value of car_statuses.visit_count
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Integer getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.visit_count
     *
     * @param visitCount the value for car_statuses.visit_count
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setVisitCount(Integer visitCount) {
        this.visitCount = visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.status
     *
     * @return the value of car_statuses.status
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.status
     *
     * @param status the value for car_statuses.status
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.last_group_id
     *
     * @return the value of car_statuses.last_group_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getLastGroupId() {
        return lastGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.last_group_id
     *
     * @param lastGroupId the value for car_statuses.last_group_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLastGroupId(String lastGroupId) {
        this.lastGroupId = lastGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.last_floor
     *
     * @return the value of car_statuses.last_floor
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getLastFloor() {
        return lastFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.last_floor
     *
     * @param lastFloor the value for car_statuses.last_floor
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLastFloor(String lastFloor) {
        this.lastFloor = lastFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.last_position_x
     *
     * @return the value of car_statuses.last_position_x
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Integer getLastPositionX() {
        return lastPositionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.last_position_x
     *
     * @param lastPositionX the value for car_statuses.last_position_x
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLastPositionX(Integer lastPositionX) {
        this.lastPositionX = lastPositionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.last_position_y
     *
     * @return the value of car_statuses.last_position_y
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Integer getLastPositionY() {
        return lastPositionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.last_position_y
     *
     * @param lastPositionY the value for car_statuses.last_position_y
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLastPositionY(Integer lastPositionY) {
        this.lastPositionY = lastPositionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.last_node_id
     *
     * @return the value of car_statuses.last_node_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getLastNodeId() {
        return lastNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.last_node_id
     *
     * @param lastNodeId the value for car_statuses.last_node_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLastNodeId(String lastNodeId) {
        this.lastNodeId = lastNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.image_url
     *
     * @return the value of car_statuses.image_url
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.image_url
     *
     * @param imageUrl the value for car_statuses.image_url
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.velocity_x
     *
     * @return the value of car_statuses.velocity_x
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Double getVelocityX() {
        return velocityX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.velocity_x
     *
     * @param velocityX the value for car_statuses.velocity_x
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setVelocityX(Double velocityX) {
        this.velocityX = velocityX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.velocity_y
     *
     * @return the value of car_statuses.velocity_y
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Double getVelocityY() {
        return velocityY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.velocity_y
     *
     * @param velocityY the value for car_statuses.velocity_y
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setVelocityY(Double velocityY) {
        this.velocityY = velocityY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_statuses.velocity_ts
     *
     * @return the value of car_statuses.velocity_ts
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Long getVelocityTs() {
        return velocityTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_statuses.velocity_ts
     *
     * @param velocityTs the value for car_statuses.velocity_ts
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setVelocityTs(Long velocityTs) {
        this.velocityTs = velocityTs;
    }
}