package com.imooc.pojo;

import java.util.Date;

public class LockLots {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.created_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.updated_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.deleted_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date deletedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.lot_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String lotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.floor
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.bt_addr
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String btAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.status
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.up_command
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String upCommand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.lock_type
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Integer lockType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.down_command
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String downCommand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.status_command
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String statusCommand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.deleted
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Byte deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.safe_radius_px
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Integer safeRadiusPx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.leave_radius_px
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Integer leaveRadiusPx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.router_ip
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String routerIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.sleep_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Integer sleepTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.lock_keys
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String lockKeys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_lots.name
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.id
     *
     * @return the value of lock_lots.id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.id
     *
     * @param id the value for lock_lots.id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.created_at
     *
     * @return the value of lock_lots.created_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.created_at
     *
     * @param createdAt the value for lock_lots.created_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.updated_at
     *
     * @return the value of lock_lots.updated_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.updated_at
     *
     * @param updatedAt the value for lock_lots.updated_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.deleted_at
     *
     * @return the value of lock_lots.deleted_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.deleted_at
     *
     * @param deletedAt the value for lock_lots.deleted_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.lot_id
     *
     * @return the value of lock_lots.lot_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getLotId() {
        return lotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.lot_id
     *
     * @param lotId the value for lock_lots.lot_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLotId(String lotId) {
        this.lotId = lotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.floor
     *
     * @return the value of lock_lots.floor
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.floor
     *
     * @param floor the value for lock_lots.floor
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setFloor(String floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.bt_addr
     *
     * @return the value of lock_lots.bt_addr
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getBtAddr() {
        return btAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.bt_addr
     *
     * @param btAddr the value for lock_lots.bt_addr
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setBtAddr(String btAddr) {
        this.btAddr = btAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.status
     *
     * @return the value of lock_lots.status
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.status
     *
     * @param status the value for lock_lots.status
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.up_command
     *
     * @return the value of lock_lots.up_command
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getUpCommand() {
        return upCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.up_command
     *
     * @param upCommand the value for lock_lots.up_command
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setUpCommand(String upCommand) {
        this.upCommand = upCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.lock_type
     *
     * @return the value of lock_lots.lock_type
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Integer getLockType() {
        return lockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.lock_type
     *
     * @param lockType the value for lock_lots.lock_type
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLockType(Integer lockType) {
        this.lockType = lockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.down_command
     *
     * @return the value of lock_lots.down_command
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getDownCommand() {
        return downCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.down_command
     *
     * @param downCommand the value for lock_lots.down_command
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setDownCommand(String downCommand) {
        this.downCommand = downCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.status_command
     *
     * @return the value of lock_lots.status_command
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getStatusCommand() {
        return statusCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.status_command
     *
     * @param statusCommand the value for lock_lots.status_command
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setStatusCommand(String statusCommand) {
        this.statusCommand = statusCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.deleted
     *
     * @return the value of lock_lots.deleted
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.deleted
     *
     * @param deleted the value for lock_lots.deleted
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.safe_radius_px
     *
     * @return the value of lock_lots.safe_radius_px
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Integer getSafeRadiusPx() {
        return safeRadiusPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.safe_radius_px
     *
     * @param safeRadiusPx the value for lock_lots.safe_radius_px
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setSafeRadiusPx(Integer safeRadiusPx) {
        this.safeRadiusPx = safeRadiusPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.leave_radius_px
     *
     * @return the value of lock_lots.leave_radius_px
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Integer getLeaveRadiusPx() {
        return leaveRadiusPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.leave_radius_px
     *
     * @param leaveRadiusPx the value for lock_lots.leave_radius_px
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLeaveRadiusPx(Integer leaveRadiusPx) {
        this.leaveRadiusPx = leaveRadiusPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.router_ip
     *
     * @return the value of lock_lots.router_ip
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getRouterIp() {
        return routerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.router_ip
     *
     * @param routerIp the value for lock_lots.router_ip
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setRouterIp(String routerIp) {
        this.routerIp = routerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.sleep_time
     *
     * @return the value of lock_lots.sleep_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Integer getSleepTime() {
        return sleepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.sleep_time
     *
     * @param sleepTime the value for lock_lots.sleep_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setSleepTime(Integer sleepTime) {
        this.sleepTime = sleepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.lock_keys
     *
     * @return the value of lock_lots.lock_keys
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getLockKeys() {
        return lockKeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.lock_keys
     *
     * @param lockKeys the value for lock_lots.lock_keys
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLockKeys(String lockKeys) {
        this.lockKeys = lockKeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_lots.name
     *
     * @return the value of lock_lots.name
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_lots.name
     *
     * @param name the value for lock_lots.name
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}