package com.imooc.pojo;

import java.util.Date;

public class LotOrders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot_orders.id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot_orders.created_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot_orders.updated_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot_orders.deleted_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Date deletedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot_orders.order_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot_orders.floor
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot_orders.lot_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String lotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot_orders.car_no
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String carNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot_orders.status
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot_orders.begin_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot_orders.end_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    private String endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot_orders.id
     *
     * @return the value of lot_orders.id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot_orders.id
     *
     * @param id the value for lot_orders.id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot_orders.created_at
     *
     * @return the value of lot_orders.created_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot_orders.created_at
     *
     * @param createdAt the value for lot_orders.created_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot_orders.updated_at
     *
     * @return the value of lot_orders.updated_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot_orders.updated_at
     *
     * @param updatedAt the value for lot_orders.updated_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot_orders.deleted_at
     *
     * @return the value of lot_orders.deleted_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot_orders.deleted_at
     *
     * @param deletedAt the value for lot_orders.deleted_at
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot_orders.order_id
     *
     * @return the value of lot_orders.order_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot_orders.order_id
     *
     * @param orderId the value for lot_orders.order_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot_orders.floor
     *
     * @return the value of lot_orders.floor
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot_orders.floor
     *
     * @param floor the value for lot_orders.floor
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setFloor(String floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot_orders.lot_id
     *
     * @return the value of lot_orders.lot_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getLotId() {
        return lotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot_orders.lot_id
     *
     * @param lotId the value for lot_orders.lot_id
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setLotId(String lotId) {
        this.lotId = lotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot_orders.car_no
     *
     * @return the value of lot_orders.car_no
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getCarNo() {
        return carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot_orders.car_no
     *
     * @param carNo the value for lot_orders.car_no
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setCarNo(String carNo) {
        this.carNo = carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot_orders.status
     *
     * @return the value of lot_orders.status
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot_orders.status
     *
     * @param status the value for lot_orders.status
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot_orders.begin_time
     *
     * @return the value of lot_orders.begin_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot_orders.begin_time
     *
     * @param beginTime the value for lot_orders.begin_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot_orders.end_time
     *
     * @return the value of lot_orders.end_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot_orders.end_time
     *
     * @param endTime the value for lot_orders.end_time
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
}