package com.imooc.mapper;

import com.imooc.pojo.CarStatuses;
import java.util.List;

public interface CarStatusesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_statuses
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_statuses
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    int insert(CarStatuses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_statuses
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    CarStatuses selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_statuses
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    List<CarStatuses> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_statuses
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    int updateByPrimaryKey(CarStatuses record);
}