package com.imooc.mapper;

import com.imooc.pojo.LotOrders;
import java.util.List;

public interface LotOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_orders
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_orders
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    int insert(LotOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_orders
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    LotOrders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_orders
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    List<LotOrders> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_orders
     *
     * @mbg.generated Sun Jul 10 13:01:36 CST 2022
     */
    int updateByPrimaryKey(LotOrders record);
}